### ISSUE TITLE
Nested form in nested form

### ISSUE THREAD

**Issue by sentbyravens** [stokarenko/dynamic-fields-for#11]
Hello!
I have that structure:
Course has_many Chapters
Chapter has_many Lessons
So my form must dynamically creates Chapters then in each chapters dynamically creates lessons.
How can I achieve that?
My view is:

<%= form_for @course do |f| %>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div class="field">
    <%= f.label :cost%>
    <%= f.text_field :cost %>
    </div>
    <div class="field">
    <%= f.label :course_picture %>
    <%= f.file_field :course_picture %>
    </div>
    <div class="field">
    <%= f.fields_for :chapters, dynamic: true do |chapter_builder| %>
          <label>Chapter:</label>

          <div class="field">
            <%= chapter_builder.label :name %>
            <%= chapter_builder.text_field :name %>
          </div>
          <div class="field">
          <%= chapter_builder.label :description%>
          <%= chapter_builder.text_area :description %>
          </div>
          <div class="field">
            
            <%= chapter_builder.fields_for :lessons, dynamic: true do |lesson_builder| %>
                <label>Lesson:</label>
                <div class="field">
                  <%= lesson_builder.label :name %>
                  <%= lesson_builder.text_field :name %>
                </div>

                <div class="field">
                  <%= lesson_builder.label :video %>
                  <%= lesson_builder.file_field :video %>
                </div>

                <div class="field">
                  <%= lesson_builder.label :text %>
                  <%= lesson_builder.text_area :text %>
                </div>

                <div class="field">
                  <%= lesson_builder.label :attachment %>
                  <%= lesson_builder.file_field :attachment %>
                </div>
                <div class="field">
                  <% lesson_builder.remove_fields_link 'Remove lesson' %>
                </div>
            <% end %>
          </div>
          <div class="field">
            <%= chapter_builder.add_fields_link :lessons, 'Add lesson' %>
          </div>
          <div class="field">
          <%= chapter_builder.remove_fields_link 'Remove chapter' %>
          </div>
    <% end %>
    </div>
    <div class="field">
    <%= f.add_fields_link :chapters, 'Add chapter' %>
    </div>
    <%= f.submit %>
<% end %>

P.S. Короче примерно суть объяснил выше, но на всякий случай нормально объясню: моя динамическая форма содержит в себе другие динамические формы (двойная вложенность). В результате на самом нижнем уровне (lessons) добавляется только один, последний добавленный урок. Как этого избежать? Спасибо

**Comment by stokarenko** [comment]
Heh, sub-dynamic fields, finally I got the case :)

Looks like the library fix should be easy, will try to think up.

P.S. Погляжу-поправлю )

**Comment by stokarenko** [comment]
Looks like fixed in v1.2.1, please check out..
